name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest",]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check something
        run: |
          echo ${{ github.workspace }}

      - name: List installed packages
        shell: bash -l {0}
        run: pip list

      - name: Test with pytest
        run: |
          python -m pytest
